import { type NextRequest, NextResponse } from "next/server"
import { createClient } from "@supabase/supabase-js"

export async function POST(request: NextRequest) {
  try {
    const { sections, userId, tipo = "analisi_lampo" } = await request.json()

    if (!userId) {
      throw new Error("userId is required for data isolation")
    }

    console.log("[submit-form] Form data received for userId:", userId, "tipo:", tipo)

    const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    })

    const formStatusColumn = tipo === "diagnosi_strategica" ? "form_status_diagnosi" : "form_status_analisi"
    const { data: utente, error: utenteError } = await supabase
      .from("utenti")
      .select(formStatusColumn)
      .eq("id", userId)
      .single()

    if (utenteError || !utente) {
      throw new Error("User not found")
    }

    if (utente[formStatusColumn] === "completed") {
      throw new Error("This form has already been completed")
    }

    const now = new Date().toISOString()

    for (const section of sections) {
      const { error } = await supabase
        .from("form")
        .upsert(
          {
            user_id: userId,
            section_index: section.sectionIndex,
            titolo: section.titolo,
            data: section.data,
            tipo,
            updated_at: now,
          },
          { onConflict: "user_id,section_index,tipo" }
        )

      if (error) throw error
    }

    console.log("[submit-form] All sections saved to form table")

    const { error: statusUpdateError } = await supabase
      .from("utenti")
      .update({ [formStatusColumn]: "completed", updated_at: now })
      .eq("id", userId)

    if (statusUpdateError) {
      console.error("[submit-form] Error updating form status:", statusUpdateError)
    } else {
      console.log("[submit-form] Form status updated to completed")
    }

    // Create diagnosi entry (enabled=false, empty content, secret_token auto-generated by DB)
    let reviewToken: string | null = null
    const { data: diagnosiRow, error: diagnosiError } = await supabase
      .from("diagnosi")
      .upsert(
        {
          user_id: userId,
          tipo,
          diagnosi: "",
          enabled: false,
        },
        { onConflict: "user_id,tipo" }
      )
      .select("secret_token")
      .single()

    if (diagnosiError) {
      console.error("[submit-form] Error creating diagnosi entry:", diagnosiError)
    } else {
      reviewToken = diagnosiRow?.secret_token ?? null
      console.log("[submit-form] Diagnosi entry created, review token:", reviewToken)
    }

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || request.nextUrl.origin
    const reviewLink = reviewToken ? `${baseUrl}/review/${reviewToken}` : null

    const sectionDataByIndex: Record<number, any> = {}
    for (const section of sections) {
      sectionDataByIndex[section.sectionIndex] = section.data
    }

    const datiAz = sectionDataByIndex[0] || {}
    const visWeb = sectionDataByIndex[1] || {}
    const acqCont = sectionDataByIndex[2] || {}
    const gestInt = sectionDataByIndex[3] || {}
    const followUp = sectionDataByIndex[4] || {}
    const competitor = sectionDataByIndex[5] || {}
    const kpi = sectionDataByIndex[6] || {}
    const obiettivi = sectionDataByIndex[7] || {}

    const webhookData = {
      userId,
      tipo,
      timestamp: now,
      reviewLink,
      sections: sectionDataByIndex,
      dati_aziendali: {
        nomeReferente: datiAz.nomeReferente,
        nomeAzienda: datiAz.nomeAzienda,
        descrizioneAzienda: datiAz.descrizioneAzienda,
        ruoloReferente: datiAz.ruoloReferente,
        emailAziendale: datiAz.emailAziendale,
        telefono: datiAz.telefono,
        sitoWeb: datiAz.sitoWeb,
        profiloSocial: datiAz.profiloSocial,
        settorePrincipale: datiAz.settorePrincipale,
        zonaOperativa: datiAz.zonaOperativa,
        rangeFatturato: datiAz.rangeFatturato,
      },
      visibilita_web: {
        sitoWebFunzionante: visWeb.sitoWebFunzionante,
        googleMyBusiness: visWeb.googleMyBusiness,
        presenzaSocial: visWeb.presenzaSocial,
      },
      acquisizione_contatti: {
        diversificazioneCanali: acqCont.diversificazioneCanali,
        nuoviContattiMese: acqCont.nuoviContattiMese,
        tassoConversione: acqCont.tassoConversione,
        formCTA: acqCont.formCTA,
      },
      gestione_interna: {
        usoCRM: gestInt.usoCRM,
        preventiviMese: gestInt.preventiviMese,
        followUpPreventivo: gestInt.followUpPreventivo,
        misurazioneTassoAccettazione: gestInt.misurazioneTassoAccettazione,
        conoscenzaColliBottiglia: gestInt.conoscenzaColliBottiglia,
      },
      follow_up: {
        velocitaRisposta: followUp.velocitaRisposta,
        chiRisponde: followUp.chiRisponde,
        sistemaFollowUp: followUp.sistemaFollowUp,
      },
      competitor: {
        competitors: competitor.competitors,
        individuazioneCompetitor: competitor.individuazioneCompetitor,
        propostoValore: competitor.propostoValore,
        visibilitaOnline: competitor.visibilitaOnline,
      },
      kpi_sintetici: {
        tempoMedioRisposta: kpi.tempoMedioRisposta,
        percentualeFollowUp: kpi.percentualeFollowUp,
        leadMensili: kpi.leadMensili,
        tassoChiusura: kpi.tassoChiusura,
      },
      obiettivi: {
        chiarezzaObiettivo: obiettivi.chiarezzaObiettivo,
        realismoObiettivo: obiettivi.realismoObiettivo,
      },
    }

    let n8nSuccess = false
    let secondWebhookSuccess = false

    const n8nWebhookUrl =
      tipo === "analisi_lampo"
        ? (process.env.N8N_WEBHOOK_ANALISI_LAMPO || "https://nextstepsrl.app.n8n.cloud/webhook/analisi-lampo")
        : (process.env.N8N_WEBHOOK_DIAGNOSI || "https://nextstepsrl.app.n8n.cloud/webhook/diagnosi")

    try {
      const n8nResponse = await fetch(n8nWebhookUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(webhookData),
      })

      if (!n8nResponse.ok) {
        const errorText = await n8nResponse.text()
        console.error("[submit-form] n8n webhook failed:", errorText)
      } else {
        console.log("[submit-form] Data sent to n8n webhook successfully")
        n8nSuccess = true
      }
    } catch (n8nError) {
      console.error("[submit-form] n8n webhook error:", n8nError)
    }

    const secondWebhookUrl = process.env.SECOND_WEBHOOK_URL
    if (secondWebhookUrl) {
      try {
        const secondWebhookResponse = await fetch(secondWebhookUrl, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(webhookData),
        })

        if (!secondWebhookResponse.ok) {
          const errorText = await secondWebhookResponse.text()
          console.error("[submit-form] Second webhook failed:", errorText)
        } else {
          console.log("[submit-form] Data sent to second webhook successfully")
          secondWebhookSuccess = true
        }
      } catch (secondWebhookError) {
        console.error("[submit-form] Second webhook error:", secondWebhookError)
      }
    }

    return NextResponse.json(
      {
        success: true,
        message: "Dati salvati con successo",
        userId,
        reviewLink,
        n8nSent: n8nSuccess,
        secondWebhookSent: secondWebhookSuccess,
      },
      { status: 200 },
    )
  } catch (error) {
    console.error("[submit-form] Error processing form:", error)
    return NextResponse.json(
      {
        success: false,
        message: "Errore durante l'invio",
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    )
  }
}

export async function GET(request: NextRequest) {
  return NextResponse.json({
    status: "active",
    endpoint: "/api/submit-form",
    message: "Questo endpoint accetta POST requests con i dati del form",
  })
}
